### ISSUE TITLE
$gatewaymac, $clientmac not available

### ISSUE THREAD

**Issue by metsis** [openwrt-routing/packages#240] opened 2016-11-11 18:14 UTC
although documentation states that $gatewaymac and $clientmac should be available on the splash page through nodogpsplash preprocessor, i am not getting them. have tested the same with e.g. $uptime, $tok and $clientip, and they work without problems. any ideas what might cause this? 

i am running version 0.9_beta9.9.9 on openwrt chaos calmer - might this be too old?

**Comment by lynxis** [comment] 2016-11-27 00:30
@metsis you might want to move this bug to the nodogsplash project (also on github). @mwarning looks like this is your bug ;).
.

**Comment by mwarning** [comment] 2016-11-27 12:26
@metsis $gatewaymac/$clientmac was implemented in v1.0.0. The changelog had a duplicate entry. It is fixed now.
Please open the ticket if the problem is still in v1.0.0.

**Closed by mwarning** 2016-11-27 12:26 UTC
